#!/usr/bin/env bash
# Writes the .env file that docker compose reads automatically. Run once.
#
#   bash docker/setup_env.sh
#
# Why this exists rather than `user: "${UID}:${GID}"` in the compose file:
# GID does not exist in bash at all (it is a zsh builtin) and UID is a bash
# special that is not exported, so compose — which reads the process environment
# — sees neither and would silently pin everyone to 1000:1000. Distinct
# LONGNAV_UID / LONGNAV_GID names in .env avoid the collision entirely.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"

# Preserve anything already set (LONGNAV_DATA in particular) rather than
# clobbering the file.
declare -A existing=()
if [ -f "${ENV_FILE}" ]; then
    while IFS='=' read -r key value; do
        [[ -z "${key}" || "${key}" == \#* ]] && continue
        existing["${key}"]="${value}"
    done < "${ENV_FILE}"
fi

existing[LONGNAV_UID]="$(id -u)"
existing[LONGNAV_GID]="$(id -g)"
: "${existing[LONGNAV_DATA]:=./data}"
# Captured before the write loop below unsets it.
data_dir="${existing[LONGNAV_DATA]}"

{
    echo "# Generated by docker/setup_env.sh — read automatically by docker compose."
    for key in LONGNAV_UID LONGNAV_GID LONGNAV_DATA; do
        echo "${key}=${existing[${key}]}"
        unset "existing[${key}]"
    done
    for key in "${!existing[@]}"; do
        echo "${key}=${existing[${key}]}"
    done
} > "${ENV_FILE}"

echo "wrote ${ENV_FILE}:"
cat "${ENV_FILE}"

# Create the bind-mount targets as *you*, before compose ever runs. Docker
# creates a missing bind-mount source itself, but does it as root, and the
# container runs as your uid — so the first dataset download would fail with
# "Permission denied" on a directory you cannot chown without host root.
DATA_DIR="${data_dir}"
case "${DATA_DIR}" in
    /*) ;;                                   # absolute, use as-is
    *)  DATA_DIR="${REPO_ROOT}/${DATA_DIR#./}" ;;
esac
mkdir -p "${DATA_DIR}" "${REPO_ROOT}/dump"
echo
echo "ensured data dir exists: ${DATA_DIR}"
