# @package _global_
task:
  run_name: mp3d_all
  wandb_project: "rl_eval"
  shard_size: 6
  subset_label: ""
  episode_json: "conf/episode_jsons/mp3d_val.json"
  output_dir: ./dump/rl_eval
  jobtype: eval
resources:
  ray_address: local
  object_spilling_directory: ./ray_object_spilling
  vlm_resource_tag: env_a
  sim_resource_tag: env_b
  master_addr: localhost
  master_port: null
  num_vlms: 4
  num_sims: 5
  vlm_conda_env: vlm_node_1016
  habitat_conda_env: vln
  vlm_gpu_fraction: 0.7
  sim_gpu_fraction: 0.14
  vlm_cpus: 4
  sim_cpus: 4
  osm_gb: 400
rollout:
  max_steps: 500
  temperature: 1.0
  action_space_str: '[stop, forward, left, right, up, down]'
  system_prompt: ${read_text:conf/prompts/objectnav_prompt.txt}
  action_space:
  - stop
  - forward
  - left
  - right
  stop_prob_threshold: 0.15
vlm:
  model_id: "Qwen/Qwen3-VL-2B-Instruct"
  attn_impl: flash_attention_2
  dtype: bfloat16
  vocab:
  - stop
  - forward
  - left
  - right
  offload_cache: false
  use_sparse: true
  save_outputs: true
sim:
  config_path: conf/habitat/objectnav_hm3d_rgbd_semantic.yaml
  workspace: null
  scenes_dir: null
  split: val
  fp_guard: false
  fn_guard: false
  voxel_kwargs: null
  output_schema:
    obs:
      rgb: true
      instr_or_goal: true
      patch_coords: false
    info:
      episode_label: true
      spl: true
      success: true
    done: true
    reward: true
    stuck: true
    fp_stop: true
  auto_flush: false
  ep_seed: 17
training:
  checkpoint: null
  load_optim: false
  load_sched: false
  learning_rate: 1.0e-05
  grad_accum_steps: 2
  mixed_precision: 'no'
  gradient_checkpointing: true
  total_optimization_steps: 20000
  save_step: 10
  peft_config:
    r: 128
    lora_alpha: 256
    lora_dropout: 0.0
    bias: none
    task_type: CAUSAL_LM
    target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
    modules_to_save: null
  rl_config:
    use_value: false
    advantage_estimator: reinforce_plus_plus_geometric_time_aware
    policy_loss_name: clip_cov
    n_rollout: 200
    n_adv: 256
    n_epoch: 2
    clip_ratio: 0.2
    clip_ratio_low: null
    clip_ratio_high: null
    clip_ratio_c: 3.0
    policy_loss:
      clip_cov_ratio: 0.0002
      clip_cov_ub: 5.0
      clip_cov_lb: 1.0
    gamma: 0.97
    lam: 0.95
    cliprange_value: 0.2
    entropy_bonus: 0.0
    use_ref: true
    kl_coeff: 0.001
    kl_target: 0.1
    global_batch_info: {}
  sft_config: null
